#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 18 11:31:37 2022

@author: student
"""


import time
import rospy
import numpy as np
import os
import sys



# os.environ['ROS_MASTER_URI']='http://172.20.10.9:11311'
# os.environ['ROS_IP']='172.20.10.8'


import tf
from geometry_msgs.msg import Twist    
from geometry_msgs.msg import Vector3
from geometry_msgs.msg import Pose, Point, Quaternion,PoseStamped 


def callback(msg):
    f = open('path.pckl', 'wb')
    pickle.dump(msg, f)
    f.close()
    print('Path saved with :',len(msg.poses), 'poses')
    
    rate.sleep()

    
    
    #msg.pose = Pose(Point(x, y, 0.),Quaternion(*tf.transformations.quaternion_from_euler(roll, pitch, yaw)))
    
    
            
            
            

if __name__ == '__main__':

    rospy.init_node('path_saver')
    rate = rospy.Rate(0.05)
    try:
        rospy.Subscriber("/trajectory", Path, callback)
        rospy.spin()
        
    except rospy.ROSInterruptException:
       
        pass
